# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34dbe43a78626352390045be3bb58946"
name = "iw-trend-configurator-remix"
application_url = "https://ac0c404c4oowc0880scows8w.3node-apps.cz"
embedded = true
handle = "iw-trend-configurator-remix-1"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_app_proxy,write_customers,write_orders,write_products,write_draft_orders"

[auth]
redirect_urls = [
  "https://ac0c404c4oowc0880scows8w.3node-apps.cz/auth/callback",
  "https://ac0c404c4oowc0880scows8w.3node-apps.cz/auth/shopify/callback",
  "https://ac0c404c4oowc0880scows8w.3node-apps.cz/api/auth/callback"
]

[app_proxy]
url = "https://ac0c404c4oowc0880scows8w.3node-apps.cz"
subpath = "configurator"
prefix = "apps"

[pos]
embedded = false
