import React from 'react'

/**
 * SVG Icons for Frame Types showing grain direction
 * Based on the provided image examples
 */

interface FrameIconProps {
  width?: number
  height?: number
}

// Type 1: All horizontal grain - top/bottom full width, sides between
export const FrameType1Icon: React.FC<FrameIconProps> = ({
  width = 80,
  height = 60,
}) => (
  <svg
    width={width}
    height={height}
    viewBox="0 0 80 60"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    {/* Outer frame */}
    <rect
      x="1"
      y="1"
      width="78"
      height="58"
      stroke="#333"
      strokeWidth="1"
      fill="none"
    />

    {/* Top piece - horizontal grain, full width */}
    <rect
      x="1"
      y="1"
      width="78"
      height="15"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="5"
        y1="8"
        x2="15"
        y2="8"
      />
      <line
        x1="20"
        y1="8"
        x2="30"
        y2="8"
      />
      <line
        x1="35"
        y1="8"
        x2="45"
        y2="8"
      />
      <line
        x1="50"
        y1="8"
        x2="60"
        y2="8"
      />
      <line
        x1="65"
        y1="8"
        x2="75"
        y2="8"
      />
    </g>

    {/* Bottom piece - horizontal grain, full width */}
    <rect
      x="1"
      y="44"
      width="78"
      height="15"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="5"
        y1="51"
        x2="15"
        y2="51"
      />
      <line
        x1="20"
        y1="51"
        x2="30"
        y2="51"
      />
      <line
        x1="35"
        y1="51"
        x2="45"
        y2="51"
      />
      <line
        x1="50"
        y1="51"
        x2="60"
        y2="51"
      />
      <line
        x1="65"
        y1="51"
        x2="75"
        y2="51"
      />
    </g>

    {/* Left piece - horizontal grain, between top/bottom */}
    <rect
      x="1"
      y="16"
      width="15"
      height="28"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="3"
        y1="22"
        x2="13"
        y2="22"
      />
      <line
        x1="3"
        y1="28"
        x2="13"
        y2="28"
      />
      <line
        x1="3"
        y1="34"
        x2="13"
        y2="34"
      />
      <line
        x1="3"
        y1="40"
        x2="13"
        y2="40"
      />
    </g>

    {/* Right piece - horizontal grain, between top/bottom */}
    <rect
      x="64"
      y="16"
      width="15"
      height="28"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="66"
        y1="22"
        x2="76"
        y2="22"
      />
      <line
        x1="66"
        y1="28"
        x2="76"
        y2="28"
      />
      <line
        x1="66"
        y1="34"
        x2="76"
        y2="34"
      />
      <line
        x1="66"
        y1="40"
        x2="76"
        y2="40"
      />
    </g>

    {/* Inner area */}
    <rect
      x="16"
      y="16"
      width="48"
      height="28"
      fill="#F8F9FA"
      stroke="#ddd"
      strokeWidth="0.5"
      strokeDasharray="2,2"
    />
  </svg>
)

// Type 2: Top/bottom horizontal grain, left/right vertical grain - top/bottom full width, sides between
export const FrameType2Icon: React.FC<FrameIconProps> = ({
  width = 80,
  height = 60,
}) => (
  <svg
    width={width}
    height={height}
    viewBox="0 0 80 60"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    {/* Outer frame */}
    <rect
      x="1"
      y="1"
      width="78"
      height="58"
      stroke="#333"
      strokeWidth="1"
      fill="none"
    />

    {/* Top piece - horizontal grain, full width */}
    <rect
      x="1"
      y="1"
      width="78"
      height="15"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="5"
        y1="8"
        x2="15"
        y2="8"
      />
      <line
        x1="20"
        y1="8"
        x2="30"
        y2="8"
      />
      <line
        x1="35"
        y1="8"
        x2="45"
        y2="8"
      />
      <line
        x1="50"
        y1="8"
        x2="60"
        y2="8"
      />
      <line
        x1="65"
        y1="8"
        x2="75"
        y2="8"
      />
    </g>

    {/* Bottom piece - horizontal grain, full width */}
    <rect
      x="1"
      y="44"
      width="78"
      height="15"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="5"
        y1="51"
        x2="15"
        y2="51"
      />
      <line
        x1="20"
        y1="51"
        x2="30"
        y2="51"
      />
      <line
        x1="35"
        y1="51"
        x2="45"
        y2="51"
      />
      <line
        x1="50"
        y1="51"
        x2="60"
        y2="51"
      />
      <line
        x1="65"
        y1="51"
        x2="75"
        y2="51"
      />
    </g>

    {/* Left piece - vertical grain, between top/bottom */}
    <rect
      x="1"
      y="16"
      width="15"
      height="28"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="5"
        y1="18"
        x2="5"
        y2="42"
      />
      <line
        x1="8"
        y1="18"
        x2="8"
        y2="42"
      />
      <line
        x1="11"
        y1="18"
        x2="11"
        y2="42"
      />
      <line
        x1="14"
        y1="18"
        x2="14"
        y2="42"
      />
    </g>

    {/* Right piece - vertical grain, between top/bottom */}
    <rect
      x="64"
      y="16"
      width="15"
      height="28"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="67"
        y1="18"
        x2="67"
        y2="42"
      />
      <line
        x1="70"
        y1="18"
        x2="70"
        y2="42"
      />
      <line
        x1="73"
        y1="18"
        x2="73"
        y2="42"
      />
      <line
        x1="76"
        y1="18"
        x2="76"
        y2="42"
      />
    </g>

    {/* Inner area */}
    <rect
      x="16"
      y="16"
      width="48"
      height="28"
      fill="#F8F9FA"
      stroke="#ddd"
      strokeWidth="0.5"
      strokeDasharray="2,2"
    />
  </svg>
)

// Type 3: Left/right full height, top/bottom between - all vertical grain
export const FrameType3Icon: React.FC<FrameIconProps> = ({
  width = 80,
  height = 60,
}) => (
  <svg
    width={width}
    height={height}
    viewBox="0 0 80 60"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    {/* Outer frame */}
    <rect
      x="1"
      y="1"
      width="78"
      height="58"
      stroke="#333"
      strokeWidth="1"
      fill="none"
    />

    {/* Left piece - vertical grain, full height */}
    <rect
      x="1"
      y="1"
      width="15"
      height="58"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="5"
        y1="3"
        x2="5"
        y2="57"
      />
      <line
        x1="8"
        y1="3"
        x2="8"
        y2="57"
      />
      <line
        x1="11"
        y1="3"
        x2="11"
        y2="57"
      />
      <line
        x1="14"
        y1="3"
        x2="14"
        y2="57"
      />
    </g>

    {/* Right piece - vertical grain, full height */}
    <rect
      x="64"
      y="1"
      width="15"
      height="58"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="67"
        y1="3"
        x2="67"
        y2="57"
      />
      <line
        x1="70"
        y1="3"
        x2="70"
        y2="57"
      />
      <line
        x1="73"
        y1="3"
        x2="73"
        y2="57"
      />
      <line
        x1="76"
        y1="3"
        x2="76"
        y2="57"
      />
    </g>

    {/* Top piece - vertical grain, between left/right */}
    <rect
      x="16"
      y="1"
      width="48"
      height="15"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="22"
        y1="3"
        x2="22"
        y2="14"
      />
      <line
        x1="28"
        y1="3"
        x2="28"
        y2="14"
      />
      <line
        x1="34"
        y1="3"
        x2="34"
        y2="14"
      />
      <line
        x1="40"
        y1="3"
        x2="40"
        y2="14"
      />
      <line
        x1="46"
        y1="3"
        x2="46"
        y2="14"
      />
      <line
        x1="52"
        y1="3"
        x2="52"
        y2="14"
      />
      <line
        x1="58"
        y1="3"
        x2="58"
        y2="14"
      />
    </g>

    {/* Bottom piece - vertical grain, between left/right */}
    <rect
      x="16"
      y="44"
      width="48"
      height="15"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="22"
        y1="46"
        x2="22"
        y2="57"
      />
      <line
        x1="28"
        y1="46"
        x2="28"
        y2="57"
      />
      <line
        x1="34"
        y1="46"
        x2="34"
        y2="57"
      />
      <line
        x1="40"
        y1="46"
        x2="40"
        y2="57"
      />
      <line
        x1="46"
        y1="46"
        x2="46"
        y2="57"
      />
      <line
        x1="52"
        y1="46"
        x2="52"
        y2="57"
      />
      <line
        x1="58"
        y1="46"
        x2="58"
        y2="57"
      />
    </g>

    {/* Inner area */}
    <rect
      x="16"
      y="16"
      width="48"
      height="28"
      fill="#F8F9FA"
      stroke="#ddd"
      strokeWidth="0.5"
      strokeDasharray="2,2"
    />
  </svg>
)

// Type 4: Left/right full height, top/bottom between - all horizontal grain
export const FrameType4Icon: React.FC<FrameIconProps> = ({
  width = 80,
  height = 60,
}) => (
  <svg
    width={width}
    height={height}
    viewBox="0 0 80 60"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    {/* Outer frame */}
    <rect
      x="1"
      y="1"
      width="78"
      height="58"
      stroke="#333"
      strokeWidth="1"
      fill="none"
    />

    {/* Left piece - horizontal grain, full height */}
    <rect
      x="1"
      y="1"
      width="15"
      height="58"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="3"
        y1="8"
        x2="13"
        y2="8"
      />
      <line
        x1="3"
        y1="15"
        x2="13"
        y2="15"
      />
      <line
        x1="3"
        y1="22"
        x2="13"
        y2="22"
      />
      <line
        x1="3"
        y1="29"
        x2="13"
        y2="29"
      />
      <line
        x1="3"
        y1="36"
        x2="13"
        y2="36"
      />
      <line
        x1="3"
        y1="43"
        x2="13"
        y2="43"
      />
      <line
        x1="3"
        y1="50"
        x2="13"
        y2="50"
      />
    </g>

    {/* Right piece - horizontal grain, full height */}
    <rect
      x="64"
      y="1"
      width="15"
      height="58"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="66"
        y1="8"
        x2="76"
        y2="8"
      />
      <line
        x1="66"
        y1="15"
        x2="76"
        y2="15"
      />
      <line
        x1="66"
        y1="22"
        x2="76"
        y2="22"
      />
      <line
        x1="66"
        y1="29"
        x2="76"
        y2="29"
      />
      <line
        x1="66"
        y1="36"
        x2="76"
        y2="36"
      />
      <line
        x1="66"
        y1="43"
        x2="76"
        y2="43"
      />
      <line
        x1="66"
        y1="50"
        x2="76"
        y2="50"
      />
    </g>

    {/* Top piece - horizontal grain, between left/right */}
    <rect
      x="16"
      y="1"
      width="48"
      height="15"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="18"
        y1="8"
        x2="28"
        y2="8"
      />
      <line
        x1="32"
        y1="8"
        x2="42"
        y2="8"
      />
      <line
        x1="46"
        y1="8"
        x2="56"
        y2="8"
      />
      <line
        x1="60"
        y1="8"
        x2="62"
        y2="8"
      />
    </g>

    {/* Bottom piece - horizontal grain, between left/right */}
    <rect
      x="16"
      y="44"
      width="48"
      height="15"
      fill="#E8F4FD"
      stroke="#333"
      strokeWidth="0.5"
    />
    <g
      stroke="#666"
      strokeWidth="0.5"
    >
      <line
        x1="18"
        y1="51"
        x2="28"
        y2="51"
      />
      <line
        x1="32"
        y1="51"
        x2="42"
        y2="51"
      />
      <line
        x1="46"
        y1="51"
        x2="56"
        y2="51"
      />
      <line
        x1="60"
        y1="51"
        x2="62"
        y2="51"
      />
    </g>

    {/* Inner area */}
    <rect
      x="16"
      y="16"
      width="48"
      height="28"
      fill="#F8F9FA"
      stroke="#ddd"
      strokeWidth="0.5"
      strokeDasharray="2,2"
    />
  </svg>
)
